name: Deploy dist folder to deploy branch

on:
  push:
    branches:
      - main # Trigger when pushing to main
  workflow_dispatch: # Trigger manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy only dist folder
        run: |
          # Create a new orphan branch
          git checkout --orphan deploy-temp
          git rm -rf .

          # Restore only dist folder
          git checkout main -- dist
          mv dist/* .
          rm -r dist

          # Commit changes
          git add .
          git commit -m "Deploy new build from main"

      - name: Push to deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git deploy-temp:deploy
